eventsReminder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reminderApp.urls', namespace='event-reminder'))
]

reminderApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'reminderApp'

urlpatterns = [
    url(r'^$', views.main_page, name='main_page'),
    url(r'^send-sms/$', views.send_sms, name='send-sms'),
]

reminderApp/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
import datetime


class Events(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextUploadingField(
        ('content'), config_name='default')
    update_date_time = models.DateTimeField(
        ('create date'), auto_now_add=True, auto_now=False)
    create_date_time = models.DateTimeField(
        ('update date'), auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

    def date_time(self):
        print(datetime.datetime.now().strftime('%A, %Y-%m-%d, %H:%M'))

reminderApp/views.py
import requests
from django.shortcuts import render, HttpResponse
from reminderApp.models import Events
from django.conf import settings
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.contrib import messages


def main_page(request):
    return render(request, 'mainPage.html')


def send_sms(request):
    if request.method == 'POST':
        message = request.POST.get('message')
        phone = request.POST.get('phone')
        sms_username = settings.SMS_USERNAME
        sms_password = settings.SMS_PASSWORD
        request = requests.get(f'https://RayganSMS.com/SendMessageWithUrl.ashx?\
                Username={sms_username}&Password={sms_password}\
                &PhoneNumber=50005858312\
                &MessageBody={message}&RecNumber={phone}\
                &Smsclass=1')
        try:
            if request is True:
                messages.success(request, 'Your message was sent successfully')
        except exception as e:
            messages.warning(request, 'Your message was not sent,\
                please try again!!! Error:{}.format(e)')
    return render(request, 'send-sms.html')


class AccountRegister:
    def __init__(self, mobile_number, email, password, confirm_password):
        self.mobile_number = mobile_number
        self.email = email
        self._password = password
        self._confirm_password = confirm_password


class PremiumAccountRegister:
    pass
    '''
        this is a class for premium account register
        and will be used to expand the project in the future.
    '''


class User(AccountRegister):
    def __init__(self, mobile_number, email, password, confirm_password):
        super().__init__(mobile_number, email, password, confirm_password)

    def check_password(self):
        if self._password == self._confirm_password:
            pass
        else:
            print('Does not match password!!!')
            self.check_password()

    def change_password(self):
        old_password = input('Please enter old password: ')
        if old_password == self._password:
            new_password = input('Please enter new password: ')
            confirm_password = input('please repeat new password:')
            if new_password == confirm_password:
                self._password = new_password
            else:
                print('Does not match!!!')
                self.change_password()
        else:
            print('wrong password!!!')
            self.change_password()

reminderApp/templates/loginPage.html
{% load static %}

<!DOCTYPE html>

<html>

    <title>

        {% block head %}
            Welcome to Events Reminder
        {% endblock head %}

    </title>

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/custom_style.css' %}">
        {% endblock css %}

        <style>

            body {
                font-family: Arial, Helvetica, sans-serif;
                background-color: black;
            }

            * {
                box-sizing: border-box;
            }

            div.a {
                text-align: center;
            }

            div.b {
                text-align: left;
            }

            div.c {
                text-align: right;
            } 

            div.d {
                text-align: justify;
            }

            body {
                color: white;
            }

            h1 {
                color: #00ff00;
            }

            p.ex {
                color: rgb(0,0,255);
            }

            /* Create two equal columns that floats next to each other */
            .column {
                float: center;
                width: 33.3333333333333333%;
                padding: 50px;
                
            }

            /* Clear floats after the columns */
            .row:after {
                content: "";
                display: table;
                clear: both;
            }

            /* Add padding to containers */
            .container {
                padding: 20px;
                background-color: #dad;
            }

            /* Full-width input fields */
            input[type=text], input[type=password] {
                width: 100%;
                padding: 10px;
                margin: 5px 0 11px 0;
                display: inline-block;
                border: none;
                background: #f1f1f1;
            }

            input[type=text]:focus, input[type=password]:focus {
                background-color: #ddd;
                outline: none;
            }

            /* Overwrite default styles of hr */
            hr {
                border: 1px solid #f1f1f1;
                margin-bottom: 5px;
            }

            /* Set a style for the submit button */
            .registerbtn {
                background-color: #7CAF50;
                color: white;
                padding: 10px 20px;
                margin: 5px 0;
                border: none;
                cursor: pointer;
                width: 100%;
                opacity: 0.9;
            }

            .registerbtn:hover {
                opacity: 1;
            }

            /* Add a blue text color to links */
            a {
                color: dodgerblue;
            }

            /* Set a grey background color and center the text of the "sign in" section */
            .signin {
                background-color: #010;
                text-align: center;
            }
            
            footer { 
                display: block;
            }
        </style>

    </head>

<div class="row">
    <div class="column" style="background-color:#ccc;">
    </div>
    <div class="column" style="background-color:#ccc;">
        <form action="/action_page.php">
            <div class="container">
                <h2>Login Form</h2>
                <p>Please fill in this form to login to your account.</p>
                <hr>

                <label for="email"><b>Email</b></label>
                <input type="text" placeholder="Enter Email" name="email" required>

                <label for="psw"><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="psw" required>

                <hr>

                <button type="submit" class="login">Login</button>
            </div>
        </form>
    </div>
    <div class="column" style="background-color:#ccc;">
    </div>
</div>
    
    <div class="a">
        <footer>
            <br>
            <p>Powerd by: OmID HoSEINI</p>
            <p>Contact information: <a href="mailto:someone@example.com">someone@example.com</a></p>
        </footer>
    </div>

    </body>

</html>

reminderApp/templates/mainPage.html
{% load static %}

<!DOCTYPE html>

<html>

    <title>

        {% block head %}
            Welcome to Events Reminder
        {% endblock head %}

    </title>

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/custom_style.css' %}">
        {% endblock css %}

        <style>

            body {
                font-family: Arial, Helvetica, sans-serif;
                background-color: black;
            }

            * {
                box-sizing: border-box;
            }

            div.a {
                text-align: center;
            }

            div.b {
                text-align: left;
            }

            div.c {
                text-align: right;
            } 

            div.d {
                text-align: justify;
            }

            body {
                color: white;
            }

            h1 {
                color: #00ff00;
            }

            p.ex {
                color: rgb(0,0,255);
            }

            /* Create two equal columns that floats next to each other */
            .column {
                float: center;
                width: 50%;
                padding: 30px;
                
            }

            /* Clear floats after the columns */
            .row:after {
                content: "";
                display: table;
                clear: both;
            }

            /* Add padding to containers */
            .container {
                padding: 10px;
                background-color: #daa;
            }

            /* Full-width input fields */
            input[type=text], input[type=password] {
                width: 100%;
                padding: 10px;
                margin: 0px 0 10px 0;
                display: inline-block;
                border: none;
                background: #f1f1f1;
            }

            input[type=text]:focus, input[type=password]:focus {
                background-color: #ddd;
                outline: none;
            }

            /* Overwrite default styles of hr */
            hr {
                border: 1px solid #f1f1f1;
                margin-bottom: 5px;
            }

            /* Set a style for the submit button */
            .registerbtn {
                background-color: #1AAA30;
                color: white;
                padding: 10px 20px;
                margin: 5px 0;
                border: none;
                cursor: pointer;
                width: 100%;
                opacity: 0.9;
            }

            .registerbtn:hover {
                opacity: 1;
            }

            /* Add a blue text color to links */
            a {
                color: dodgerblue;
            }

            /* Set a grey background color and center the text of the "sign in" section */
            .signin {
                background-color: #010;
                text-align: center;
            }
            
            footer { 
                display: block;
            }
        </style>

    </head>

<div class="a">
    <h2>Events Reminder</h2>
</div>

<div class="row">

        <div class="column" style="background-color:#aaa;">
            <img src="smiley.gif" alt="Smiley face" width="42" height="42">
            <h2><b>About servise: </b></h2>
            <h4>You can create your personal events here, they will be reminded you by sending via SMS or EMAIL.</h4>
            <br>
            <br>
            <br>
            <h4><b>How to use: </b></h4>
            <h4>You should register account than login and created your events in your dashboard</h4>
        </div>

        <div class="column" style="background-color:#bbb;">
            <form action="/action_page.php">
                <div class="container">
                    <div class="container signin">
                    <p>Already have an account? <a href="#">Sign in</a>.</p>
                    </div>

                    <h2>Register Form</h2>
                    <p>Please fill in this form to create an account.</p>
                    <hr>

                    <label for="email"><b>Email</b></label>
                    <input type="text" placeholder="Enter Email" name="email" required>

                    <label for="mobile_number"><b>Mobile Number</b></label>
                    <input type="text" placeholder="Enter Mobile Number" name="mobile_number" required>

                    <label for="psw"><b>Password</b></label>
                    <input type="password" placeholder="Enter Password" name="psw" required>

                    <label for="psw-repeat"><b>Repeat Password</b></label>
                    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
                    <hr>
                    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

                    <button type="submit" class="registerbtn">Register</button>
                </div>


            </form>
        </div>
    </div>
    
    <div class="a">
        <footer>
            <br>
            <p>Powerd by: OmID HoSEINI</p>
            <p>Contact information: <a href="mailto:someone@example.com">someone@example.com</a></p>
        </footer>
    </div>

    </body>

</html>

reminderApp/templates/send-sms.html
<!DOCTYPE html>
<html>
<head>
    <title>send sms</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>

    <div class="container">
        <div class="row">
            {% if messages %}

                {% for message in messages %}
                
                    <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true"></span></button>
                        <strong>{{message}}</strong>
                    </div>
                
                {% endfor %}

            {% else %}
            
                <form method='post' class="col s12" action="{% url 'event-reminder:send-sms' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="input-field col s6">
                            <i class="material-icons prefix">text_fields</i>
                            <input name='message' id="icon_prefix" type="text" class="validate">
                            <label for="icon_prefix">Message</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">phone</i>
                            <input name="phone" id="icon_telephone" type="tel" class="validate">
                            <label for="icon_telephone">Telephone</label>
                        </div>
                    </div>
                    <input type="submit" name="submit" class="btn right">
                </form>

            {% endif %}

          </div>
        </div>
    </div>
</body>
</html>